var CAREERS = [
    "Administrador",
    "Advogado",
    "Aeronauta",
    "Arquivista-Técnico de Arquivo",
    "Artista/Técnico em espetáculos de diversões",
    "Assistente Social",
    "Atleta Profissional de Futebol",
    "Bibliotecário'",
    "Biomédico",
    "Biólogo",
    "Bombeiro Civil",
    "Comerciário",
    "Contabilista",
    "Corretor de Imóveis",
    "Corretor de Seguros",
    "Despachante Aduaneiro",
    "Engenheiro Agrônomo",
    "Economista Doméstico",
    "Economista",
    "Educacador Físico",
    "Empregado Doméstico",
    "Enfermagem",
    "Enfermólogo",
    "Engenharia de Segurança",
    "Fisioterapeuta e Terapeuta Ocupacional",
    "Farmacêutico",
    "Fonoaudiólogo",
    "Garimpeiro",
    "Geógrafo",
    "Geólogo",
    "Guardador e Lavador de Veículos",
    "Instrutor de Trânsito",
    "Jornalista",
    "Leiloeiro",
    "Leiloeiro Rural",
    "Massagista",
    "Médico",
    "Museólogo",
    "Nutricionista",
    "Oceanógrafo",
    "Odontologia",
    "Orientador Educacional",
    "Pescador Profissional",
    "Psicologia",
    "Publicitário-Agenciador de Propaganda",
    "Químico",
    "Radialista",
    "Representantes Comerciais Autônomos",
    "Repentista",
    "Sociólogo",
    "Sommelier",
    "Taxista",
    "Tradutor e Intérprete da Língua Brasileira de Sinais - LIBRAS",
    "Técnico em Administração",
    "Técnico Industrial",
    "Técnico em Prótese Dentária",
    "Técnico em Radiologia",
    "Turismólogo",
    "Zootecnista"
];

let getCareers = () => {
    return CAREERS;
};

export default {getCareers};